### ISSUE TITLE
Monocromatic problem

### ISSUE THREAD

**Issue by EidrianGM** [mr-ubik/atom-ubik-neon-syntax#4] opened 2017-01-17 19:12 UTC
I really don't know why (I have just started learning python and stuff), but after installing your theme (which I liked a lot), I get this (all in the same color, and can't see highlighted the selected text):

![screenshot from 2017-01-17 20-08-49](https://cloud.githubusercontent.com/assets/6950240/22035594/cb875006-dcf0-11e6-994e-d85be06da46d.png)

Let me know if you need more info.
Thanks

**Comment by mr-ubik** [comment] 2017-01-17 21:20
Check out this [closed issue](https://github.com/mr-ubik/atom-ubik-neon-syntax/issues/2), the problem is due to Atom and can be fixed via updating to version 1.13

**Closed as completed** 2017-01-17 22:29 UTC
Labels: duplicate
